{% set name = "pyscal" %}
{% set version = "2.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/srmnitc/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 4006e2a358d9a58b00a9efc927cf9a6be9d914bc9d98e377443f4ad4857ebdaa
  patches:
    - remove_win.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - pip
    - matplotlib-base >=3
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pyscal
  commands:
    - pip check

about:
  home: https://pyscal.com
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Python library written in C++ for calculation of local atomic structural environment

  description: |
    pyscal is a python module for the calculation of local 
    atomic structural environments including Steinhardt's bond 
    orientational order parameters [1] during post-processing 
    of atomistic simulation data. The core functionality of 
    pyscal is written in C++ with python wrappers using 
    pybind11 which allows for fast calculations with possibilities 
    for easy expansion in python.
  doc_url: https://pyscal.com
  dev_url: https://github.com/srmnitc/pyscal/

extra:
  recipe-maintainers:
    - jan-janssen
    - srmnitc
