{% set name = "pyscal" %}
{% set version = "2.10.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/srmnitc/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 124f9b9df65024a93ea71123ce7c3e3cca89880bc8954babdef852ea9b177fc8

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py2k]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - cmake
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - pip
    - ase
    - matplotlib-base >=3
    - ipywidgets
    - plotly
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pyscal
  commands:
    - pip check

about:
  home: https://pyscal.org
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Python library written in C++ for calculation of local atomic structural environment

  description: |
    pyscal is a python module for the calculation of local 
    atomic structural environments including Steinhardt's bond 
    orientational order parameters [1] during post-processing 
    of atomistic simulation data. The core functionality of 
    pyscal is written in C++ with python wrappers using 
    pybind11 which allows for fast calculations with possibilities 
    for easy expansion in python.
  doc_url: https://pyscal.org
  dev_url: https://github.com/srmnitc/pyscal/

extra:
  recipe-maintainers:
    - jan-janssen
    - srmnitc
